# Generated by Django 2.2.7 on 2019-11-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191129_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('sub_title', models.CharField(max_length=127)),
                ('link', models.CharField(max_length=127)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
